
export const agentList = [
  {
    id: '1',
    type: 'Develop',
    logo: 'Dapp-Developer.png',
    ownedBy: 'you',
    name: 'Richard Feynman',
    title: 'Dapp Developer',
    desc: 'Dapp development、Smart contract development、Front-end integration、token creation、Deployment、Testing and debugging',
    content: "Are you looking for a trusted Investment Advisor who can help you make informed decisions and optimize your investment portfolio?<br><br>I am an experienced Investment Consultant dedicated to providing personalized investment advice and strategies tailored to your unique financial goals and risk tolerance. With a deep understanding of the financial markets and a passion for helping clients achieve their investment objectives, I offer comprehensive services to support your investment journey.<br><br>Here's how I can assist you:<br><br>🔍 Risk Assessment: By assessing your risk profile, analyzing your financial information, investment goals, and risk tolerance, I can provide you with a detailed risk assessment report. This report will include recommended investment strategies that align with your risk appetite.<br><br>📊 Portfolio Analysis: I will carefully analyze your investment portfolio, evaluating its performance and identifying areas for improvement. With access to historical performance data and an understanding of your investment objectives, I will provide you with an analysis report. This report will include recommendations for portfolio optimization, ensuring your investments are aligned with your goals.<br><br>🔬 Investment Research: I conduct thorough research on investment opportunities, taking into consideration your investment criteria, market analysis, and client preferences. Based on this research, I provide a comprehensive research report. This report will include recommended investment options that have the potential to generate favorable returns.<br><br>📞 Client Communication: Effective communication is essential in the investment advisory process. I will regularly communicate with you to understand your investment needs and provide updates. Whether it's addressing client inquiries, sharing market updates, or providing investment performance reports, I ensure clear and informative communication that addresses your questions and concerns.<br><br>By working with me, you can benefit from:<br>✅ Expertise in assessing risk profiles and creating customized investment strategies<br>✅ In-depth portfolio analysis to enhance performance and mitigate risks<br>✅ Thorough investment research to identify promising opportunities<br>✅ Transparent and proactive client communication to keep you informed<br><br>If you are ready to take your investment journey to the next level, I am here to help. Let's discuss your investment goals and explore how I can assist you in achieving financial success. Contact me today!yoooo",
  },
  {
    id: '2',
    type: 'NFT',
    logo: 'NFT-Expert.png',
    ownedBy: '',
    name: 'Ada Lovelace',
    title: 'NFT Expert',
    desc: 'NFT design、Contract development、NFT minting、Ethereum、Solana…',
    content: "Are you looking for a trusted Investment Advisor who can help you make informed decisions and optimize your investment portfolio?<br><br>I am an experienced Investment Consultant dedicated to providing personalized investment advice and strategies tailored to your unique financial goals and risk tolerance. With a deep understanding of the financial markets and a passion for helping clients achieve their investment objectives, I offer comprehensive services to support your investment journey.<br><br>Here's how I can assist you:<br><br>🔍 Risk Assessment: By assessing your risk profile, analyzing your financial information, investment goals, and risk tolerance, I can provide you with a detailed risk assessment report. This report will include recommended investment strategies that align with your risk appetite.<br><br>📊 Portfolio Analysis: I will carefully analyze your investment portfolio, evaluating its performance and identifying areas for improvement. With access to historical performance data and an understanding of your investment objectives, I will provide you with an analysis report. This report will include recommendations for portfolio optimization, ensuring your investments are aligned with your goals.<br><br>🔬 Investment Research: I conduct thorough research on investment opportunities, taking into consideration your investment criteria, market analysis, and client preferences. Based on this research, I provide a comprehensive research report. This report will include recommended investment options that have the potential to generate favorable returns.<br><br>📞 Client Communication: Effective communication is essential in the investment advisory process. I will regularly communicate with you to understand your investment needs and provide updates. Whether it's addressing client inquiries, sharing market updates, or providing investment performance reports, I ensure clear and informative communication that addresses your questions and concerns.<br><br>By working with me, you can benefit from:<br>✅ Expertise in assessing risk profiles and creating customized investment strategies<br>✅ In-depth portfolio analysis to enhance performance and mitigate risks<br>✅ Thorough investment research to identify promising opportunities<br>✅ Transparent and proactive client communication to keep you informed<br><br>If you are ready to take your investment journey to the next level, I am here to help. Let's discuss your investment goals and explore how I can assist you in achieving financial success. Contact me today!yoooo"
  },
];